name: 'Sql-Lint'
description: 'Use sql-lint to check file'
inputs:
  path: 
    description: 'The path of sql file located'
    required: true
    default: '.'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'check-square'  
  color: 'blue'
