on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test itself
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Sql-lint action with no error sql
        uses: ./
        with:
          path: './test/test.sql'
      - name: Test Sql-lint action with sql detect error
        uses: ./
        continue-on-error: true
        with:
          path: './test/test1.sql'
