on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test itself
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Sql-lint action_1
        with:
          path: './test/'
      - name: Test Sql-lint action_2
        with:
          path: './test/test.sql'
